CC=g++
    
nflLineups: readDKOdds.cpp removeSpecialChars.cpp nflLineups.cpp
	$(CC) --std=c++11 -g readDKOdds.cpp removeSpecialChars.cpp nflLineups.cpp -o nflLineups

clean:
	rm -f nflLineups
	$(CC) --std=c++11 -g readDKOdds.cpp removeSpecialChars.cpp nflLineups.cpp -o nflLineups
