CC=g++
    
nhlLineups: readDKOdds.cpp removeSpecialChars.cpp nhlLineups.cpp
	$(CC) --std=c++11 readDKOdds.cpp removeSpecialChars.cpp nhlLineups.cpp -o nhlLineups

clean:
	rm -f nhlLineups
	$(CC) --std=c++11 readDKOdds.cpp removeSpecialChars.cpp nhlLineups.cpp -o nhlLineups
